import type { Fleet, Visit } from './types';

export const fleets: Fleet[] = [
  { id: 'F1234', plate: 'ABC-1D23', equipmentType: 'Carreta', carrier: 'Trans-Veloz' },
  { id: 'F5678', plate: 'EFG-4H56', equipmentType: 'Cavalo', carrier: 'Log-Rápido' },
  { id: 'F9012', plate: 'IJK-7L89', equipmentType: 'Bitrem', carrier: 'Carga-Express' },
  { id: 'F3456', plate: 'MNO-1P23', equipmentType: 'Carreta', carrier: 'Trans-Veloz' },
  { id: 'F7890', plate: 'QRS-4T56', equipmentType: 'Rodotrem', carrier: 'Log-Rápido' },
  { id: 'F1122', plate: 'UVW-7X89', equipmentType: 'Cavalo', carrier: 'Carga-Express' },
];

export const visits: Visit[] = [
    {
    id: 'V007',
    fleetId: 'F1122',
    plate: 'UVW-7X89',
    equipmentType: 'Cavalo',
    orderType: ['Inspeção'],
    status: 'Em Fila',
    arrivalTimestamp: new Date().getTime() - 1 * 60 * 60 * 1000, // 1 hour ago
    notes: 'Inspeção de rotina antes da viagem.',
    workshop: 'Vale das Carretas',
    serviceHistory: [],
  },
  {
    id: 'V008',
    fleetId: 'F9012',
    plate: 'IJK-7L89',
    equipmentType: 'Bitrem',
    orderType: ['Calibragem'],
    status: 'Em Manutenção',
    arrivalTimestamp: new Date().getTime() - 4 * 60 * 60 * 1000, // 4 hours ago
    maintenanceStartTimestamp: new Date().getTime() - 3 * 60 * 60 * 1000,
    boxEntryTimestamp: new Date().getTime() - 3 * 60 * 60 * 1000,
    boxNumber: '05',
    notes: 'Calibrar todos os pneus.',
    workshop: 'CMC',
    serviceHistory: [],
  },
  {
    id: 'V009',
    fleetId: 'F3456',
    plate: 'MNO-1P23',
    equipmentType: 'Carreta',
    orderType: ['Corretiva', 'Inspeção'],
    status: 'Aguardando Peça',
    arrivalTimestamp: new Date().getTime() - 2 * 24 * 60 * 60 * 1000, // 2 days ago
    maintenanceStartTimestamp: new Date().getTime() - 1.5 * 24 * 60 * 60 * 1000,
    awaitingPartTimestamp: new Date().getTime() - 1 * 24 * 60 * 60 * 1000,
    boxEntryTimestamp: new Date().getTime() - 1.5 * 24 * 60 * 60 * 1000,
    boxNumber: '04',
    notes: 'Luz de freio não acende. Fazer inspeção completa após o reparo.',
    servicePerformed: 'TROCA DA LÂMPADA DE FREIO',
    partUsed: 'LÂMPADA 2 POLOS',
    workshop: 'Monte Líbano',
    serviceHistory: [],
  },
  {
    id: 'V001',
    fleetId: 'F1234',
    plate: 'ABC-1D23',
    equipmentType: 'Carreta',
    orderType: ['Corretiva'],
    status: 'Em Manutenção',
    arrivalTimestamp: new Date('2024-07-20T08:00:00').getTime(),
    maintenanceStartTimestamp: new Date('2024-07-20T09:30:00').getTime(),
    boxEntryTimestamp: new Date('2024-07-20T09:15:00').getTime(),
    boxNumber: '01',
    notes: 'Problema no sistema de freios.',
    workshop: 'Monte Líbano',
    serviceHistory: [],
  },
  {
    id: 'V002',
    fleetId: 'F5678',
    plate: 'EFG-4H56',
    equipmentType: 'Cavalo',
    orderType: ['Preventiva'],
    status: 'Em Fila',
    arrivalTimestamp: new Date().getTime() - 2 * 60 * 60 * 1000, // 2 hours ago
    notes: 'Revisão periódica.',
    workshop: 'Vale das Carretas',
    serviceHistory: [],
  },
  {
    id: 'V003',
    fleetId: 'F9012',
    plate: 'IJK-7L89',
    equipmentType: 'Bitrem',
    orderType: ['Preditiva'],
    status: 'Aguardando Peça',
    arrivalTimestamp: new Date('2024-07-19T14:00:00').getTime(),
    maintenanceStartTimestamp: new Date('2024-07-19T15:00:00').getTime(),
    awaitingPartTimestamp: new Date('2024-07-19T18:30:00').getTime(),
    boxEntryTimestamp: new Date('2024-07-19T14:45:00').getTime(),
    boxNumber: '03',
    notes: 'Sensor de temperatura do motor precisa ser substituído.',
    workshop: 'CMC',
    serviceHistory: [],
  },
  {
    id: 'V004',
    fleetId: 'F3456',
    plate: 'MNO-1P23',
    equipmentType: 'Carreta',
    orderType: ['Preventiva'],
    status: 'Finalizado',
    arrivalTimestamp: new Date('2024-07-18T10:00:00').getTime(),
    maintenanceStartTimestamp: new Date('2024-07-18T10:30:00').getTime(),
    finishTimestamp: new Date('2024-07-18T18:00:00').getTime(),
    boxEntryTimestamp: new Date('2024-07-18T10:15:00').getTime(),
    boxNumber: '02',
    notes: 'Troca de óleo e filtros concluída.',
    servicePerformed: 'Troca de óleo e todos os filtros do motor.',
    partUsed: 'Kit Filtros (Ar, Óleo, Combustível)',
    partQuantity: 1,
    workshop: 'Monte Líbano',
    serviceHistory: [],
  },
  {
    id: 'V005',
    fleetId: 'F1234',
    plate: 'ABC-1D23',
    equipmentType: 'Carreta',
    orderType: ['Corretiva'],
    status: 'Finalizado',
    arrivalTimestamp: new Date('2024-05-10T09:00:00').getTime(),
    maintenanceStartTimestamp: new Date('2024-05-10T09:45:00').getTime(),
    finishTimestamp: new Date('2024-05-11T11:00:00').getTime(),
    boxEntryTimestamp: new Date('2024-05-10T09:30:00').getTime(),
    boxNumber: '01',
    notes: 'Reparo no sistema elétrico.',
    servicePerformed: 'Substituição do chicote principal do motor.',
    partUsed: 'Chicote Principal Scania 124',
    partQuantity: 1,
    workshop: 'Vale das Carretas',
    serviceHistory: [],
  },
   {
    id: 'V006',
    fleetId: 'F7890',
    plate: 'QRS-4T56',
    equipmentType: 'Rodotrem',
    orderType: ['Corretiva'],
    status: 'Em Fila',
    arrivalTimestamp: new Date().getTime() - 12 * 60 * 60 * 1000, // 12 hours ago (overtime)
    notes: 'Falha na suspensão.',
    workshop: 'CMC',
    serviceHistory: [],
  },
];
